# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI  # name of the workflow

# Trigger the workflow on any push to the main branch or pull request
on:
  push:       # This is an Event which will be trigger
    branches:
      - main
  pull_request:   # This is an Event which will be trigger
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu_latest  # Runs on ubuntu container

    steps:
      # Step1 - Check out the code from the repository
      - name: Check ot code
        uses: actions/checkout@v2   # Prebuild action in github which can checkout the code in repository

      # Step2 - Set up python environment
      - name: Set up Python
        uses: actions/setup-python@v2  # Prebuild action in github which can setup python environment
        with:
          python-version: '3.8'
          
      # Step3 - Install dependencies
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # step4: Run tests
      - name: Run tests
        run: pytest
